apiVersion: v1 # Static
kind: Secret # Static
metadata:
  name: Name Of Secret
  namespace: Namespace
  deletionGracePeriodSeconds: x #number of seconds
  annotations:
    key: "value"
    # ...
  labels:
    key: "value"
    # ...
  ownerReference:
    apiVersion: API version
    kind: Kind
    name: Name
    uid: UID
    blockOwnerDeletion: bool # true or false
    controller: bool # true or false
immutable: bool # true or false
type: Type
data:
  key: value
  key: |
    key=value
    key=value
    # ...
  # ...
stringData:
  key: value\
  # ...