# cert-issuer-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: envoy-gateway-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: karol27100@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
        gatewayHTTPRoute:
          parentRefs:
          - kind: Gateway
            name: platform-gateway
            namespace: envoy-gateway-system